---

- name: Install NGINX
  apt:
    name: nginx

- name: Replace default html file
  template: >
    src=index.html.j2
    dest=/var/www/html/index.html

- name: Copy image
  copy: >
    src=Hakuna-Matata.jpg
    dest=/var/www/html/Hakuna-Matata.jpg

- name: Restart NGINX
  service:
    name: nginx
    state: reloaded
